/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package mx.itson.BancoDiftware.ui;

/**
 *  JDialog que permite la edicion de una solicitud de credito.
 * @author Erick Garza, Emmanuel Rivas y Carlos Cadena.
 */
public class EditarSoliForm extends javax.swing.JDialog {

    /**
     * Creates new form EditarSoliForm
     */
    public EditarSoliForm(java.awt.Frame parent, boolean modal, int id) {
        super(parent, modal);
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        txtMonto = new javax.swing.JPanel();
        lbl = new javax.swing.JLabel();
        lbl1 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        btnAceptarD = new javax.swing.JButton();
        lbl2 = new javax.swing.JLabel();
        jSeparator2 = new javax.swing.JSeparator();
        TxtMonts = new javax.swing.JTextField();
        txtTarjeta = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        txtMonto.setBackground(new java.awt.Color(255, 255, 255));

        lbl.setBackground(new java.awt.Color(112, 145, 255));
        lbl.setFont(new java.awt.Font("Lucida Sans", 1, 24)); // NOI18N
        lbl.setForeground(new java.awt.Color(112, 145, 255));
        lbl.setText("Editar deposito");

        lbl1.setBackground(new java.awt.Color(112, 145, 255));
        lbl1.setFont(new java.awt.Font("Lucida Sans", 1, 15)); // NOI18N
        lbl1.setForeground(new java.awt.Color(112, 145, 255));
        lbl1.setText("Monto:");

        jSeparator1.setBackground(new java.awt.Color(112, 145, 255));
        jSeparator1.setForeground(new java.awt.Color(112, 145, 255));

        btnAceptarD.setBackground(new java.awt.Color(81, 84, 255));
        btnAceptarD.setFont(new java.awt.Font("Lucida Sans", 1, 14)); // NOI18N
        btnAceptarD.setForeground(new java.awt.Color(255, 255, 255));
        btnAceptarD.setText("Aceptar");
        btnAceptarD.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAceptarDActionPerformed(evt);
            }
        });

        lbl2.setBackground(new java.awt.Color(112, 145, 255));
        lbl2.setFont(new java.awt.Font("Lucida Sans", 1, 15)); // NOI18N
        lbl2.setForeground(new java.awt.Color(112, 145, 255));
        lbl2.setText("Numero de tarjeta:");

        jSeparator2.setBackground(new java.awt.Color(112, 145, 255));
        jSeparator2.setForeground(new java.awt.Color(112, 145, 255));

        TxtMonts.setBackground(new java.awt.Color(255, 255, 255));
        TxtMonts.setForeground(new java.awt.Color(0, 0, 0));
        TxtMonts.setBorder(null);

        txtTarjeta.setBackground(new java.awt.Color(255, 255, 255));
        txtTarjeta.setForeground(new java.awt.Color(0, 0, 0));
        txtTarjeta.setBorder(null);
        txtTarjeta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtTarjetaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout txtMontoLayout = new javax.swing.GroupLayout(txtMonto);
        txtMonto.setLayout(txtMontoLayout);
        txtMontoLayout.setHorizontalGroup(
            txtMontoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(txtMontoLayout.createSequentialGroup()
                .addGroup(txtMontoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(txtMontoLayout.createSequentialGroup()
                        .addGap(158, 158, 158)
                        .addComponent(btnAceptarD, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(txtMontoLayout.createSequentialGroup()
                        .addGap(187, 187, 187)
                        .addComponent(lbl1))
                    .addGroup(txtMontoLayout.createSequentialGroup()
                        .addGap(148, 148, 148)
                        .addComponent(lbl2))
                    .addGroup(txtMontoLayout.createSequentialGroup()
                        .addGap(104, 104, 104)
                        .addGroup(txtMontoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jSeparator1, javax.swing.GroupLayout.DEFAULT_SIZE, 235, Short.MAX_VALUE)
                            .addComponent(jSeparator2, javax.swing.GroupLayout.DEFAULT_SIZE, 235, Short.MAX_VALUE)
                            .addComponent(TxtMonts, javax.swing.GroupLayout.PREFERRED_SIZE, 227, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtTarjeta)))
                    .addGroup(txtMontoLayout.createSequentialGroup()
                        .addGap(132, 132, 132)
                        .addComponent(lbl)))
                .addContainerGap(110, Short.MAX_VALUE))
        );
        txtMontoLayout.setVerticalGroup(
            txtMontoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(txtMontoLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lbl)
                .addGap(29, 29, 29)
                .addComponent(lbl2)
                .addGap(20, 20, 20)
                .addComponent(txtTarjeta, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lbl1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 30, Short.MAX_VALUE)
                .addComponent(TxtMonts, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(27, 27, 27)
                .addComponent(btnAceptarD, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(31, 31, 31))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(txtMonto, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(txtMonto, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnAceptarDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAceptarDActionPerformed
      
        
        
        
        
        
        
        
        
        
        
        
        
        /*
        boolean resultado = this.id == 0?

        if(resultado){
            JOptionPane.showMessageDialog(this, "El deposito se realizo correctamente", "Deposito realizado", JOptionPane.INFORMATION_MESSAGE );
            dispose();
        } else {
            JOptionPane.showMessageDialog(this, "Ocurrió un error en el proceso", "Error", JOptionPane.ERROR_MESSAGE);
            dispose();
        }
        */
    }//GEN-LAST:event_btnAceptarDActionPerformed

    private void txtTarjetaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtTarjetaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtTarjetaActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(EditarSoliForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(EditarSoliForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(EditarSoliForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(EditarSoliForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                EditarSoliForm dialog = new EditarSoliForm(new javax.swing.JFrame(), true, 0);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField TxtMonts;
    private javax.swing.JButton btnAceptarD;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JLabel lbl;
    private javax.swing.JLabel lbl1;
    private javax.swing.JLabel lbl2;
    private javax.swing.JPanel txtMonto;
    private javax.swing.JTextField txtTarjeta;
    // End of variables declaration//GEN-END:variables
}
